server {
    listen 80;
    server_name thk-holdings-hcm.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name thk-holdings-hcm.site;

    ssl_certificate /etc/nginx/ssl/thk-holdings-hcm.site.crt;
    ssl_certificate_key /etc/nginx/ssl/thk-holdings-hcm.site.key;

    # SSL optimization
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    client_max_body_size 100M;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
