services:
  frontend:
    build:
      context: ../quiz-fe
      dockerfile: Dockerfile
      target: dev
    container_name: quiz-fe-local
    volumes:
      - ../quiz-fe:/app
      - fe_node_modules:/app/node_modules
    command: ["yarn", "dev", "--host"]
    ports:
      - "5173:5173"
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  fe_node_modules:
